metric: COCO
num_classes: 1

TrainDataset:
  name: COCODataSet
  image_dir: temp2_pd_coco_noBox
  anno_path: temp2_pd_coco_noBox/instances_train2017.json
  dataset_dir: /media/ssd4t/liaolin/01_box
  data_fields: ['image',  'gt_class', 'gt_poly'] #data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: test_Strap_R10_2times_pd_coco
  anno_path: test_Strap_R10_2times_pd_coco/instances_train2017.json
  dataset_dir: /media/ssd4t/liaolin/01_box #test_Strap_R10_2times_pd_coco /media/ssd4t/liaolin/01_box/test_Strap_R10_2times/meiruian_20210819
  allow_empty: true
  data_fields: ['image',  'gt_class', 'gt_poly']

TestDataset:
  name: ImageFolder
  anno_path: instances_train2017.json # also support txt (like VOC's label_list.txt)
  dataset_dir: /media/ssd4t/liaolin/01_box/train_Strap_R10_2times/geek_tote_palletize_20210710 # if set, anno_path will be 'dataset_dir/anno_path'
